/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.prcentroeducativo.BD.ControladorDao.Entidades.Formularios;

import com.prcentroeducativo.BD.ControladorDao.AlumnoDaoImp;
import com.prcentroeducativo.BD.ControladorDao.Entidades.Alumno;
import com.prcentroeducativo.BD.ControladorDao.Entidades.CursoAcademico;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author javip
 */
public class frmInternoAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmInternoAlumnos
     */
    public frmInternoAlumnos() {
        initComponents();
        configTabla();
        cargaTabla();
    }

     private void configTabla(){ 
    
     String col[]={"ID","DNI","NOMBRE","APELLIDO1","APELLIDO2","FNACIMIENTO","TELEFONO","EMAIL","DIRECCION","CP","POBLACION","PROVINCIA"};
        
        DefaultTableModel modelo=new DefaultTableModel(col,0){
        
              @Override
              public boolean isCellEditable(int row, int column){
                  return false;
              }
        
        };
        
        jtAlumnos.setModel(modelo);
        jtAlumnos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
        //configuro evento valor cambiado...
/*        jtCursos.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            System.out.println(jtCursos.getValueAt(jtCursos.getSelectedRow(), 0).toString());
            setCampos();
        }
    });
  */      
}
   
   
    private void cargaTabla(){
        DefaultTableModel modelo=(DefaultTableModel)jtAlumnos.getModel();
        
        AlumnoDaoImp alumControler=AlumnoDaoImp.getInstance();
        String[] fila=new String[12];
        
        modelo.setNumRows(0);
        try{
            List<Alumno> lst=alumControler.getAll();
            
            for( Alumno alum :lst){
                fila[0]=""+alum.getId();
                fila[1]=""+alum.getDni();
                fila[2]=""+alum.getNombre();
                fila[3]=""+alum.getApellido1() + " " + alum.getApellido2();
                fila[4]=""+alum.getFnacimiento();
                fila[5]=""+alum.getTelefono();
                fila[6]=""+alum.getEmail();
                fila[7]=""+alum.getDireccion();
                fila[8]=""+alum.getCp();
                fila[9]=""+alum.getPoblacion();
                fila[10]=""+alum.getProvincia();
                modelo.addRow(fila);
            }
            //selecciono la primera fila
           jtAlumnos.setRowSelectionInterval(0,0); 
           
        }catch(Exception e){
            System.out.println("Error:"+e.getMessage());
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        txtBuscar1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlumnos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        jtxtApellido2 = new javax.swing.JTextField();
        jtxtDni = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jtxtFechaNac = new javax.swing.JTextField();
        jtxtTelefono = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtDireccion = new javax.swing.JTextField();
        jtxtCp = new javax.swing.JTextField();
        jtxtPoblacion = new javax.swing.JTextField();
        jtxtProvincia = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alumnos");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnActualizar.setText("Actualiza");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        txtBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar1ActionPerformed(evt);
            }
        });
        txtBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscar1KeyPressed(evt);
            }
        });
        jPanel3.add(txtBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 90, -1));

        jtAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAlumnos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 610, 339));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 690, 420));

        jLabel12.setText("CP");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel10.setText("Direccion");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel3.setText("Id");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel1.setText("Buscar");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 50, -1));

        jLabel11.setText("Telefono");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel14.setText("Email");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel7.setText("Apellidos");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 20));

        jLabel9.setText("Fecha Nac.");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel8.setText("Dni");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jLabel13.setText("Poblacion");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel15.setText("Provincia");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        txtNombre2.setText("jTextField21");
        jPanel2.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jtxtApellido2.setText("jTextField21");
        jPanel2.add(jtxtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 210, 30));

        jtxtDni.setText("jTextField21");
        jPanel2.add(jtxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        txtId.setText("jTextField21");
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jtxtFechaNac.setText("jTextField21");
        jPanel2.add(jtxtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jtxtTelefono.setText("jTextField21");
        jPanel2.add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jtxtEmail.setText("jTextField21");
        jPanel2.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jtxtDireccion.setText("jTextField21");
        jPanel2.add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jtxtCp.setText("jTextField21");
        jPanel2.add(jtxtCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jtxtPoblacion.setText("jTextField21");
        jPanel2.add(jtxtPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jtxtProvincia.setText("jTextField21");
        jPanel2.add(jtxtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAlumnosMouseClicked
        // TODO add your handling code here:
        setCampos();
        if (evt.getClickCount()==2){
            // System.out.println("Doble click.....");
            //Cargar el detalle de un alumno
            /*JDialog frame=new JDialog(this,"Detalle Alumno",true);

            jpAlumnoDetalle panel=new jpAlumnoDetalle();

            int idseleccion=Integer.parseInt(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(), 0).toString());

            panel.CargaDetalle(idseleccion);

            frame.getContentPane().add(panel);
            frame.pack();
            frame.setVisible(true);
            */
        }
    }//GEN-LAST:event_jtAlumnosMouseClicked

    private void txtBuscar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar1KeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            DefaultTableModel modelo=(DefaultTableModel) jtAlumnos.getModel();
            TableRowSorter<TableModel> trSorter = new TableRowSorter<TableModel>(modelo);

            jtAlumnos.setRowSorter(trSorter);

            if (txtBuscar1.getText().length()==0) {
                trSorter.setRowFilter(null);
            }else{

                trSorter.setRowFilter(RowFilter.regexFilter(txtBuscar1.getText().trim()));
            }

        }
    }//GEN-LAST:event_txtBuscar1KeyPressed

    private void txtBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        AlumnoDaoImp alum=AlumnoDaoImp.getInstance();
        
        try{
            alum.update(getCampos());
            JOptionPane.showMessageDialog(this, "Curso actualizado correctamente");
            int fila=jtAlumnos.getSelectedRow();
            cargaTabla();
            jtAlumnos.setRowSelectionInterval(fila,fila);
        }catch(Exception e){
            System.out.println("Error:"+e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
        //agregar un cursoacademico nuevo
        AlumnoDaoImp alum=AlumnoDaoImp.getInstance();

        try{
            alum.add(getCampos());
            JOptionPane.showMessageDialog(this, "Curso agregado correctamente");
            cargaTabla();

        }catch(Exception e){
            System.out.println("Error:"+e.getMessage());
        }
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private Alumno getCampos(){
        Alumno alum=new Alumno();
        alum.setNombre(txtNombre2.getText());
        alum.setId(Integer.parseInt(txtId.getText()));
        alum.setApellido2(jtxtApellido2.getText());
        alum.setCp(Integer.parseInt(jtxtCp.getText()));
        alum.setDni(jtxtDni.getText());
        alum.setFnacimiento(Date.valueOf(jtxtFechaNac.getText()));
        alum.setTelefono(Integer.parseInt(jtxtTelefono.getText()));
        alum.setEmail(jtxtEmail.getText());
        alum.setDireccion(jtxtDireccion.getText());
        alum.setPoblacion(jtxtPoblacion.getText());
        alum.setProvincia(jtxtProvincia.getText());
        
        return alum;        
    }
    
    /**
     * Establece los valores de los txt con los 
     * valores de la fisa actual
     */
    private void setCampos(){
        
        
        txtNombre2.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(),2 ).toString());
        txtId.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(), 0).toString());
        jtxtDni.setText((jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(),1).toString()));
        jtxtApellido2.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(),3 ).toString());
        jtxtFechaNac.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(),4).toString());
        jtxtTelefono.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(), 5).toString());
        jtxtEmail.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(), 6).toString());
        jtxtDireccion.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(), 7).toString());
        jtxtCp.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(), 8).toString());
        jtxtPoblacion.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(), 9).toString());
        jtxtProvincia.setText(jtAlumnos.getValueAt(jtAlumnos.getSelectedRow(), 10).toString());
          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAlumnos;
    private javax.swing.JTextField jtxtApellido2;
    private javax.swing.JTextField jtxtCp;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtDni;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFechaNac;
    private javax.swing.JTextField jtxtPoblacion;
    private javax.swing.JTextField jtxtProvincia;
    private javax.swing.JTextField jtxtTelefono;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre2;
    // End of variables declaration//GEN-END:variables
}
